/tmp/slurmd/job44792183/slurm_script: line 87: SCALE: command not found
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
        main()main_worker(args)

  File "examples/test_pitts_tokyo.py", line 178, in main
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
        return __factory[name](root, *args, **kwargs)dataset = datasets.create(args.dataset, root, scale=args.scale)

  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 231369 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 231368) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test_pitts_tokyo.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-17_00:52:38
  host      : c0804a-s35.ufhpc
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 231370)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-17_00:52:38
  host      : c0804a-s35.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 231371)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-17_00:52:38
  host      : c0804a-s35.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 231368)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/tmp/slurmd/job44792183/slurm_script: line 87: SCALE: command not found
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
        main_worker(args)main()

  File "examples/test_pitts_tokyo.py", line 272, in main_worker
  File "examples/test_pitts_tokyo.py", line 178, in main
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    return __factory[name](root, *args, **kwargs)
      File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
        raise RuntimeError("Dataset not found.")self.arrange()

    RuntimeError  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
main():     
Dataset not found.self.arrange()  File "examples/test_pitts_tokyo.py", line 178, in main


  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 319623) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test_pitts_tokyo.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-17_01:14:51
  host      : c0804a-s35.ufhpc
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 319624)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-17_01:14:51
  host      : c0804a-s35.ufhpc
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 319625)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-09-17_01:14:51
  host      : c0804a-s35.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 319626)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-17_01:14:51
  host      : c0804a-s35.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 319623)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/tmp/slurmd/job44792183/slurm_script: line 87: SCALE: command not found
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main()    
main()      File "examples/test_pitts_tokyo.py", line 178, in main

main_worker(args)  File "examples/test_pitts_tokyo.py", line 178, in main

  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    main_worker(args)    
dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)      File "examples/test_pitts_tokyo.py", line 272, in main_worker

main()  File "examples/test_pitts_tokyo.py", line 39, in get_data

  File "examples/test_pitts_tokyo.py", line 178, in main
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
            dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)dataset = datasets.create(args.dataset, root, scale=args.scale)dataset = datasets.create(args.dataset, root, scale=args.scale)


  File "examples/test_pitts_tokyo.py", line 39, in get_data
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
        return __factory[name](root, *args, **kwargs)return __factory[name](root, *args, **kwargs)

  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    return __factory[name](root, *args, **kwargs)
          File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
self.arrange()self.arrange()

  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
            self.arrange()raise RuntimeError("Dataset not found.")raise RuntimeError("Dataset not found.")


  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
RuntimeErrorRuntimeError:     : Dataset not found.raise RuntimeError("Dataset not found.")Dataset not found.


RuntimeError: Dataset not found.
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 433375 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 433374) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test_pitts_tokyo.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-17_01:37:04
  host      : c0804a-s35.ufhpc
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 433376)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-17_01:37:04
  host      : c0804a-s35.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 433377)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-17_01:37:04
  host      : c0804a-s35.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 433374)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/tmp/slurmd/job44792183/slurm_script: line 87: SCALE: command not found
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
        main_worker(args)dataset = datasets.create(args.dataset, root, scale=args.scale)

  File "examples/test_pitts_tokyo.py", line 272, in main_worker
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 524041) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test_pitts_tokyo.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-17_01:59:22
  host      : c0804a-s35.ufhpc
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 524042)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-17_01:59:22
  host      : c0804a-s35.ufhpc
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 524043)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-09-17_01:59:22
  host      : c0804a-s35.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 524044)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-17_01:59:22
  host      : c0804a-s35.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 524041)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/tmp/slurmd/job44792183/slurm_script: line 87: SCALE: command not found
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
        main()main()

  File "examples/test_pitts_tokyo.py", line 178, in main
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
        main_worker(args)main_worker(args)

  File "examples/test_pitts_tokyo.py", line 272, in main_worker
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
        dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)

  File "examples/test_pitts_tokyo.py", line 39, in get_data
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
        return __factory[name](root, *args, **kwargs)return __factory[name](root, *args, **kwargs)

  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
        self.arrange()self.arrange()

  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
        raise RuntimeError("Dataset not found.")raise RuntimeError("Dataset not found.")

RuntimeErrorRuntimeError: : Dataset not found.Dataset not found.

    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 610257) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test_pitts_tokyo.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-17_02:21:35
  host      : c0804a-s35.ufhpc
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 610258)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-17_02:21:35
  host      : c0804a-s35.ufhpc
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 610259)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-09-17_02:21:35
  host      : c0804a-s35.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 610260)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-17_02:21:35
  host      : c0804a-s35.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 610257)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/tmp/slurmd/job44792183/slurm_script: line 87: SCALE: command not found
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    self.arrange()
      File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 696904) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test_pitts_tokyo.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-17_02:43:48
  host      : c0804a-s35.ufhpc
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 696905)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-17_02:43:48
  host      : c0804a-s35.ufhpc
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 696906)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-09-17_02:43:48
  host      : c0804a-s35.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 696907)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-17_02:43:48
  host      : c0804a-s35.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 696904)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/tmp/slurmd/job44792183/slurm_script: line 87: SCALE: command not found
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
        main()main()

  File "examples/test_pitts_tokyo.py", line 178, in main
  File "examples/test_pitts_tokyo.py", line 178, in main
        main_worker(args)main_worker(args)

  File "examples/test_pitts_tokyo.py", line 272, in main_worker
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
        main()    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 178, in main

  File "examples/test_pitts_tokyo.py", line 39, in get_data
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
            main_worker(args)dataset = datasets.create(args.dataset, root, scale=args.scale)dataset = datasets.create(args.dataset, root, scale=args.scale)


  File "examples/test_pitts_tokyo.py", line 272, in main_worker
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
        dataset = datasets.create(args.dataset, root, scale=args.scale)return __factory[name](root, *args, **kwargs)

  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
        self.arrange()self.arrange()    

raise RuntimeError("Dataset not found.")  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange

RuntimeError: Dataset not found.
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 781767) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test_pitts_tokyo.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-17_03:06:11
  host      : c0804a-s35.ufhpc
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 781768)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-17_03:06:11
  host      : c0804a-s35.ufhpc
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 781769)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-09-17_03:06:11
  host      : c0804a-s35.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 781770)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-17_03:06:11
  host      : c0804a-s35.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 781767)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/tmp/slurmd/job44792183/slurm_script: line 87: SCALE: command not found
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main()
      File "examples/test_pitts_tokyo.py", line 178, in main
main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
        main_worker(args)dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)

  File "examples/test_pitts_tokyo.py", line 272, in main_worker
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
        dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)dataset = datasets.create(args.dataset, root, scale=args.scale)

  File "examples/test_pitts_tokyo.py", line 39, in get_data
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
        dataset = datasets.create(args.dataset, root, scale=args.scale)return __factory[name](root, *args, **kwargs)

  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()    
return __factory[name](root, *args, **kwargs)  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange

  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
        raise RuntimeError("Dataset not found.")self.arrange()

RuntimeError  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
: Dataset not found.
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 867948) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test_pitts_tokyo.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-17_03:28:24
  host      : c0804a-s35.ufhpc
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 867949)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-17_03:28:24
  host      : c0804a-s35.ufhpc
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 867950)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-09-17_03:28:24
  host      : c0804a-s35.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 867951)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-17_03:28:24
  host      : c0804a-s35.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 867948)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/tmp/slurmd/job44792183/slurm_script: line 87: SCALE: command not found
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
        main()dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)

  File "examples/test_pitts_tokyo.py", line 178, in main
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
        main_worker(args)dataset = datasets.create(args.dataset, root, scale=args.scale)

  File "examples/test_pitts_tokyo.py", line 272, in main_worker
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)    
return __factory[name](root, *args, **kwargs)  File "examples/test_pitts_tokyo.py", line 39, in get_data

      File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    dataset = datasets.create(args.dataset, root, scale=args.scale)
      File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 954753) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test_pitts_tokyo.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-17_03:50:47
  host      : c0804a-s35.ufhpc
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 954754)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-17_03:50:47
  host      : c0804a-s35.ufhpc
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 954755)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-09-17_03:50:47
  host      : c0804a-s35.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 954756)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-17_03:50:47
  host      : c0804a-s35.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 954753)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/tmp/slurmd/job44792183/slurm_script: line 87: SCALE: command not found
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
        main()dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)

  File "examples/test_pitts_tokyo.py", line 178, in main
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
        dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)return __factory[name](root, *args, **kwargs)

  File "examples/test_pitts_tokyo.py", line 39, in get_data
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1036818) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test_pitts_tokyo.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-17_04:13:15
  host      : c0804a-s35.ufhpc
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1036819)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-17_04:13:15
  host      : c0804a-s35.ufhpc
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1036820)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-09-17_04:13:15
  host      : c0804a-s35.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1036821)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-17_04:13:15
  host      : c0804a-s35.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1036818)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/tmp/slurmd/job44792183/slurm_script: line 87: SCALE: command not found
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    main()
      File "examples/test_pitts_tokyo.py", line 178, in main
dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)    
dataset = datasets.create(args.dataset, root, scale=args.scale)  File "examples/test_pitts_tokyo.py", line 39, in get_data

      File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    main()main_worker(args)

  File "examples/test_pitts_tokyo.py", line 178, in main
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
        self.arrange()dataset = datasets.create(args.dataset, root, scale=args.scale)

  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
        return __factory[name](root, *args, **kwargs)self.arrange()

  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1124353) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test_pitts_tokyo.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-17_04:35:38
  host      : c0804a-s35.ufhpc
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1124354)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-17_04:35:38
  host      : c0804a-s35.ufhpc
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1124355)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-09-17_04:35:38
  host      : c0804a-s35.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1124356)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-17_04:35:38
  host      : c0804a-s35.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1124353)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/tmp/slurmd/job44792183/slurm_script: line 87: SCALE: command not found
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
      File "examples/test_pitts_tokyo.py", line 39, in get_data
main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    return __factory[name](root, *args, **kwargs)    
main_worker(args)  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__

  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
      File "examples/test_pitts_tokyo.py", line 39, in get_data
self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    dataset = datasets.create(args.dataset, root, scale=args.scale)
      File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1209931) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test_pitts_tokyo.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-17_04:57:46
  host      : c0804a-s35.ufhpc
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1209932)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-17_04:57:46
  host      : c0804a-s35.ufhpc
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1209933)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-09-17_04:57:46
  host      : c0804a-s35.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1209934)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-17_04:57:46
  host      : c0804a-s35.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1209931)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/tmp/slurmd/job44792183/slurm_script: line 87: SCALE: command not found
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
      File "examples/test_pitts_tokyo.py", line 272, in main_worker
main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
        dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)main_worker(args)

  File "examples/test_pitts_tokyo.py", line 39, in get_data
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
        dataset = datasets.create(args.dataset, root, scale=args.scale)dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)

  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
        return __factory[name](root, *args, **kwargs)return __factory[name](root, *args, **kwargs)

  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
        self.arrange()self.arrange()

  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
        raise RuntimeError("Dataset not found.")raise RuntimeError("Dataset not found.")

RuntimeErrorRuntimeError: : Dataset not found.Dataset not found.

    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1294224) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test_pitts_tokyo.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-17_05:20:04
  host      : c0804a-s35.ufhpc
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1294225)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-17_05:20:04
  host      : c0804a-s35.ufhpc
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1294226)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-09-17_05:20:04
  host      : c0804a-s35.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1294227)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-17_05:20:04
  host      : c0804a-s35.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1294224)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/tmp/slurmd/job44792183/slurm_script: line 87: SCALE: command not found
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
        dataset = datasets.create(args.dataset, root, scale=args.scale)dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)

  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    return __factory[name](root, *args, **kwargs)
      File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()
      File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
        return __factory[name](root, *args, **kwargs)raise RuntimeError("Dataset not found.")

  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
RuntimeError: Dataset not found.
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1379226) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test_pitts_tokyo.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-17_05:42:07
  host      : c0804a-s35.ufhpc
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1379227)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-17_05:42:07
  host      : c0804a-s35.ufhpc
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1379228)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-09-17_05:42:07
  host      : c0804a-s35.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1379229)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-17_05:42:07
  host      : c0804a-s35.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1379226)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/tmp/slurmd/job44792183/slurm_script: line 87: SCALE: command not found
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
        main()dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)

  File "examples/test_pitts_tokyo.py", line 178, in main
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    Traceback (most recent call last):
dataset = datasets.create(args.dataset, root, scale=args.scale)  File "examples/test_pitts_tokyo.py", line 331, in <module>

  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset = datasets.create(args.dataset, root, scale=args.scale)
      File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
        self.arrange()return __factory[name](root, *args, **kwargs)

  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
        self.arrange()dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)

  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1464538) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test_pitts_tokyo.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-17_06:04:35
  host      : c0804a-s35.ufhpc
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1464539)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-17_06:04:35
  host      : c0804a-s35.ufhpc
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1464540)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-09-17_06:04:35
  host      : c0804a-s35.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1464541)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-17_06:04:35
  host      : c0804a-s35.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1464538)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/tmp/slurmd/job44792183/slurm_script: line 87: SCALE: command not found
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    dataset = datasets.create(args.dataset, root, scale=args.scale)    
main()  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create

  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
        main_worker(args)return __factory[name](root, *args, **kwargs)

  File "examples/test_pitts_tokyo.py", line 272, in main_worker
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
        self.arrange()dataset = datasets.create(args.dataset, root, scale=args.scale)

  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    raise RuntimeError("Dataset not found.")
RuntimeError:     Dataset not found.return __factory[name](root, *args, **kwargs)

      File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    main_worker(args)
  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1554372) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test_pitts_tokyo.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-17_06:26:43
  host      : c0804a-s35.ufhpc
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1554374)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-17_06:26:43
  host      : c0804a-s35.ufhpc
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1554375)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-09-17_06:26:43
  host      : c0804a-s35.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1554376)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-17_06:26:43
  host      : c0804a-s35.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1554372)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/tmp/slurmd/job44792183/slurm_script: line 87: SCALE: command not found
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
Traceback (most recent call last):
  File "examples/test_pitts_tokyo.py", line 331, in <module>
  File "examples/test_pitts_tokyo.py", line 331, in <module>
        main()main()

  File "examples/test_pitts_tokyo.py", line 178, in main
  File "examples/test_pitts_tokyo.py", line 178, in main
        main_worker(args)    main_worker(args)
main()
  File "examples/test_pitts_tokyo.py", line 272, in main_worker

  File "examples/test_pitts_tokyo.py", line 272, in main_worker
  File "examples/test_pitts_tokyo.py", line 178, in main
    main()
  File "examples/test_pitts_tokyo.py", line 178, in main
    dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)
  File "examples/test_pitts_tokyo.py", line 39, in get_data
        main_worker(args)dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)    

main_worker(args)  File "examples/test_pitts_tokyo.py", line 272, in main_worker
  File "examples/test_pitts_tokyo.py", line 39, in get_data

  File "examples/test_pitts_tokyo.py", line 272, in main_worker
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
        dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)dataset, pitts_train, train_extract_loader, test_loader_q, test_loader_db = get_data(args)

  File "examples/test_pitts_tokyo.py", line 39, in get_data
  File "examples/test_pitts_tokyo.py", line 39, in get_data
        return __factory[name](root, *args, **kwargs)dataset = datasets.create(args.dataset, root, scale=args.scale)

  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    dataset = datasets.create(args.dataset, root, scale=args.scale)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
    dataset = datasets.create(args.dataset, root, scale=args.scale)
      File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/__init__.py", line 31, in create
return __factory[name](root, *args, **kwargs)
      File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
    return __factory[name](root, *args, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 30, in __init__
        raise RuntimeError("Dataset not found.")self.arrange()

RuntimeError  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    : self.arrange()Dataset not found.

  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
    self.arrange()
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/datasets/tokyo.py", line 39, in arrange
        raise RuntimeError("Dataset not found.")raise RuntimeError("Dataset not found.")

RuntimeErrorRuntimeError: : Dataset not found.Dataset not found.

    raise RuntimeError("Dataset not found.")
RuntimeError: Dataset not found.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1638055) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test_pitts_tokyo.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-17_06:49:11
  host      : c0804a-s35.ufhpc
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1638056)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-17_06:49:11
  host      : c0804a-s35.ufhpc
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1638057)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-09-17_06:49:11
  host      : c0804a-s35.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1638058)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-17_06:49:11
  host      : c0804a-s35.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1638055)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
